export const crawlerDefaults = Object.freeze({
  maxUrls: 5000,
  concurrency: 2,
  maxConcurrentPerHost: 2,
  userAgent: 'LocalSEOGeoAudit/0.1 (+localhost)',
  robotsUserAgent: 'LocalSEOGeoAudit',
  targetPagesPerSecond: 0,
  maxAttempts: 3,
  retryBaseDelayMs: 1000,
  retryMaxDelayMs: 30000,
  retryStatusCodes: [408, 429, 500, 502, 503, 504],
  requestTimeoutMs: 15000,
  heartbeatIntervalMs: 5000,
  staleHeartbeatMs: 60000,
  processingTimeoutMs: 120000,
  crawlDelayMs: 0,
  maxSitemapUrls: null,
  maxSitemaps: 100,
  sitemapBatchSize: 1000,
  enableTemplateSampling: true,
  enablePlaywrightSampling: false,
  enableLighthouseSampling: false,
  sampleUrlsPerTemplate: 5,
  maxTemplateSamplesTotal: 200,
  lighthouseDevice: 'mobile',
  lighthouseCategories: ['performance', 'accessibility', 'best-practices', 'seo'],
  lighthouseTimeoutMs: 60000,
  playwrightTimeoutMs: 30000,
  renderSettlingMaxMs: 6000,
  renderSettlingIntervalMs: 500,
  renderSettlingMaxSnapshots: 13,
  renderSettlingStableSnapshots: 3,
  renderSettlingMinimumObservationMs: 4000,
  maxConcurrentRenderedPages: 1,
  collectScreenshots: false,
  sampleOnlyIndexable: true,
  shardCount: 32
});
